export enum Role {
  PI = 'PI',
  CO_INVESTIGATOR = 'CO_INVESTIGATOR',
  ASSISTANT = 'ASSISTANT',
  REVIEWER = 'REVIEWER',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum InternalStage {
  PROPOSAL = 'PROPOSAL',
  ETHICS_REVIEW = 'ETHICS_REVIEW',
  DATA_COLLECTION = 'DATA_COLLECTION',
  DATA_ANALYSIS = 'DATA_ANALYSIS',
  INTERNAL_REVIEW = 'INTERNAL_REVIEW',
  PUBLISHED = 'PUBLISHED',
}

export enum EthicalStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum OutputType {
  JOURNAL = 'JOURNAL',
  CONFERENCE = 'CONFERENCE',
  REPORT = 'REPORT',
}
